### ISSUE TITLE
群晖有部署教程吗？吗怕简单写个呢？这个实在是不会。。。

### ISSUE THREAD

**Issue by oemsys** [yigger/JZ-back#2]
群晖有部署教程吗？吗怕简单写个呢？这个实在是不会。。。

**Comment by oemsys** [comment]
DOCKER？

**Comment by oemsys** [comment]
![image](https://user-images.githubusercontent.com/32034317/84964352-7f4c0a80-b13e-11ea-846c-731cefa1c2a0.png)
![image](https://user-images.githubusercontent.com/32034317/84964439-b3bfc680-b13e-11ea-80ae-d8de112455ad.png)

一直报错，您可以帮忙做个DOCKER吗？

**Comment by yigger** [comment]
@oemsys 这一块还不是很完善哦，不是搭起来就能用的，需要自己二次开发一下

**Comment by oemsys** [comment]
坐等更新？？？二次开发，我是不会，没那本事，等您这好吧~！不知道您还在开发，后续有会有更新吗？

**Comment by oemsys** [comment]
有更新好吗？？坐不住了~！

**Comment by yigger** [comment]
> 有更新好吗？？坐不住了~！

哪有这么快，我都是业余时间在维护，距离完成可能要半年到一年时间吧～

**Comment by oemsys** [comment]
2023我又来了，好了吗？
